[alias]
br = "build --release"
bt = "build --timings"
brt = "build --release --timings"


[build]
target = [
    "x86_64-pc-windows-msvc",
    # "x86_64-unknown-linux-gnu",
    # "aarch64-apple-darwin",
]
jobs = -1


[env]
RUST_LOG = "debug"
# RUST_BACKTRACE = "true"
RUST_BACKTRACE = "full"
