name: Rust CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: rustream

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: rustream-linux
            asset_name: rustream-linux-amd64
          - os: windows-latest
            artifact_name: rustream-windows.exe
            asset_name: rustream-windows-amd64.exe
          - os: macos-latest
            artifact_name: rustream-macos
            asset_name: rustream-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev pkg-config

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Fetch dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test --verbose

      - name: Build Release Binary
        shell: bash
        run: |
            if [ "${{ runner.os }}" == "Windows" ]; then
            export RUSTFLAGS="-A warnings"
            cargo build --release
            else
            RUSTFLAGS="-A warnings" cargo build --release
            fi

      - name: Rename binary
        if: github.ref == 'refs/heads/main'
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            cp target/release/${{ env.BINARY_NAME }}.exe ${{ matrix.artifact_name }}
          else
            cp target/release/${{ env.BINARY_NAME }} ${{ matrix.artifact_name }}
          fi

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$tag" >> $GITHUB_OUTPUT

      - name: Calculate next version
        id: next_version
        run: |
          current_tag="${{ steps.get_tag.outputs.latest_tag }}"
          current_tag="${current_tag#v}"
          IFS='.' read -ra PARTS <<< "$current_tag"
          major=${PARTS[0]:-0}
          minor=${PARTS[1]:-0}
          patch=${PARTS[2]:-0}
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.next_version.outputs.version }}
          name: Release v${{ steps.next_version.outputs.version }}
          files: |
            rustream-linux-amd64
            rustream-windows-amd64.exe
            rustream-macos-amd64
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
